CC=g++
CXXFLAGS=-g -std=c++11 -Wall

all: Arm.o Run.o main.o
	$(CC) $(CXXFLAGS) Arm.o Run.o main.o -o ConsoleTest1

clean:
	rm -f ConsoleTest1
	rm -f *.o
=======
all:
	g++ main.cpp -o ConsoleTest1

clean:
	rm -f ConsoleTest1
